import { copyFile, mkdir, mkdtemp, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const MARKER = 'Generated by scripts/generate-tagging-fixture.ts.'
const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const TESTFILES = join(ROOT, 'testfiles')
const FOLDER_NAME = 'Various Artists - Tagging Edge Cases (2024) [FLAC]'
const DESTINATION = join(TESTFILES, FOLDER_NAME)

interface FixtureTrack {
  disc: 1 | 2
  file: string
  tags: string[]
  picture?: boolean
}

const commonTags = [
  'ALBUM=Tagging Edge Cases',
  'ALBUMARTIST=Various Artists',
  'DATE=2024-05-17',
  'EDITIONTITLE=Deluxe “QA” Edition',
  'LABEL=Edge Case Records',
  'CATALOGNUMBER=EDGE-001',
  'UPC=000123456789',
  'GENRE=Classical; Electronic',
  'RELEASETYPE=Compilation',
  'COMMENT=Short synthetic files for Gravlax end-to-end tests.',
  'URL=https://example.invalid/tagging-edge-cases'
]

const tracks: FixtureTrack[] = [
  {
    disc: 1,
    file: '01 - conductor duplicated as main.flac',
    picture: true,
    tags: [
      'TRACKNUMBER=01/12',
      'DISCNUMBER=1/2',
      'TITLE=I. Prelude',
      'ARTIST=North Sea Orchestra & Ada Lovelace',
      'CONDUCTOR=Ada Lovelace',
      'COMPOSER=Bach, Johann Sebastian',
      'ISRC=GB-GRX-24-00001',
      'REPLAYGAIN_TRACK_GAIN=-7.00 dB',
      'REPLAYGAIN_TRACK_PEAK=0.9876',
      'REPLAYGAIN_ALBUM_GAIN=-6.00 dB',
      'REPLAYGAIN_ALBUM_PEAK=0.9999',
      'X-GRAVLAX-TEST=keep this unmanaged tag',
      'COVERART=legacy-cover-placeholder',
      'COVERARTMIME=image/png'
    ]
  },
  {
    disc: 1,
    file: '02 - same main and composer.flac',
    tags: [
      'TRACKNUMBER=2',
      'DISCNUMBER=1',
      'TITLE=Songwriter Collision',
      'ARTIST=Adele',
      'COMPOSER=Adele'
    ]
  },
  {
    disc: 1,
    file: '03 - sole main is conductor.flac',
    tags: [
      'TRACKNUMBER=03',
      'DISCNUMBER=01',
      'TITLE=The Last Main Must Stay',
      'ARTIST=Solo Maestro',
      'CONDUCTOR=Solo Maestro'
    ]
  },
  {
    disc: 1,
    file: '04 - role delimiters.flac',
    tags: [
      'TRACKNUMBER=4/12',
      'DISCNUMBER=1/2',
      'TITLE=Names That Must Not Split',
      'ARTIST=QA Quartet',
      'COMPOSER=Earth, Wind & Fire',
      'COMPOSER=Writer One; Writer Two / Writer Three',
      'COMPOSER=writer one',
      'CONDUCTOR=Maestro, Jr.',
      'GENRE=Classical / Choral'
    ]
  },
  {
    disc: 1,
    file: '05 - artist and title features.flac',
    tags: [
      'TRACKNUMBER=05',
      'DISCNUMBER=1',
      'TITLE=Collaboration (feat. Erin)',
      'ARTIST=Alice, Bob ft. Carol & Dave'
    ]
  },
  {
    disc: 1,
    file: '06 - preserve old artist.flac',
    tags: [
      'TRACKNUMBER=6',
      'DISCNUMBER=1',
      'TITLE=Composer-only Proposal Exercise',
      'ARTIST=Legacy Lead',
      'COMPOSER=No Lead Writer',
      'PRODUCER=Ignored Producer',
      'ARRANGER=Ignored Arranger'
    ]
  },
  {
    disc: 2,
    file: '01 - unicode duplicates.flac',
    tags: [
      'TRACKNUMBER=01',
      'DISCNUMBER=2',
      'TITLE=Unicode Normalization',
      'ARTIST=Björk',
      'ARTIST=BJÖRK',
      'COMPOSER=O’Connor',
      "COMPOSER=O'Connor"
    ]
  },
  {
    disc: 2,
    file: '02 - punctuation in artist names.flac',
    tags: [
      'TRACKNUMBER=2',
      'DISCNUMBER=2',
      'TITLE=Slash and Ampersand Ambiguity',
      'ARTIST=AC/DC & Earth, Wind & Fire',
      'REMIXER=Ignored Remixer',
      'DJMIXER=Ignored DJ Compiler',
      'LABEL=Other Imprint'
    ]
  },
  {
    disc: 2,
    file: '03 - spaced aliases.flac',
    tags: [
      'TRACK NUMBER=03/12',
      'DISC NUMBER=02/02',
      'TITLE=Spaced Tag Aliases',
      'ARTIST=Alias Artist',
      'ALBUM ARTIST=Various Artists',
      'YEAR=2024',
      'CATNO=EDGE-001',
      'BARCODE=000123456789',
      'DESCRIPTION=Short synthetic files for Gravlax end-to-end tests.',
      'WEBSITE=https://example.invalid/alias'
    ]
  },
  {
    disc: 2,
    file: '04 - four title guests.flac',
    tags: [
      'TRACKNUMBER=4',
      'DISCNUMBER=2',
      'TITLE=Guest Overflow feat. Guest A, Guest B, Guest C & Guest D',
      'ARTIST=Lead Artist',
      'DATE=2025-01-02'
    ]
  },
  {
    disc: 2,
    file: '05 - missing album artist.flac',
    tags: [
      'TRACKNUMBER=5',
      'DISCNUMBER=2',
      'TITLE=Missing Album Artist on One File',
      'ARTIST=Track-only Artist',
      'ALBUMARTIST='
    ]
  },
  {
    disc: 2,
    file: '06 - fallback and missing number.flac',
    tags: [
      'DISCNUMBER=2',
      'TITLE=Album-Artist Fallback with No Track Number',
      'ALBUM ARTIST=Various Artists',
      'COMPOSER=Fallback Composer'
    ]
  }
]

await ensureTool('flac')
await ensureTool('metaflac')
await mkdir(TESTFILES, { recursive: true })

const staging = await mkdtemp(join(TESTFILES, '.tagging-fixture-'))
const sourceWav = join(staging, 'tone.wav')
const sourceFlac = join(staging, 'tone.flac')

try {
  await writeToneWav(sourceWav)
  await run('flac', [
    '--silent',
    '--force',
    `--output-name=${sourceFlac}`,
    sourceWav
  ])

  const releaseRoot = join(staging, FOLDER_NAME)
  const coverPath = join(releaseRoot, 'cover.png')
  await mkdir(join(releaseRoot, 'CD1'), { recursive: true })
  await mkdir(join(releaseRoot, 'CD2'), { recursive: true })
  await writeFile(
    coverPath,
    Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
      'base64'
    )
  )

  for (const track of tracks) {
    const path = join(releaseRoot, `CD${track.disc}`, track.file)
    await copyFile(sourceFlac, path)
    const tags = commonTags
      .filter((tag) => !overridden(tag, track.tags))
      .concat(track.tags)
    const args = ['--remove-all-tags', ...tags.map((tag) => `--set-tag=${tag}`)]
    if (track.picture) args.push(`--import-picture-from=${coverPath}`)
    args.push(path)
    await run('metaflac', args)
    await run('flac', ['--test', '--silent', path])
  }

  await writeFile(join(releaseRoot, 'GRAVLAX TAGGING FIXTURE.txt'), fixtureNotes())
  await replaceGeneratedFixture(releaseRoot)
} finally {
  await rm(staging, { recursive: true, force: true })
}

console.log(DESTINATION)

function overridden(common: string, local: string[]): boolean {
  const key = canonicalTagKey(common)
  return local.some((tag) => {
    return canonicalTagKey(tag) === key
  })
}

function canonicalTagKey(tag: string): string {
  const raw = tag.slice(0, tag.indexOf('=')).replaceAll(' ', '').toUpperCase()
  if (raw === 'YEAR') return 'DATE'
  if (raw === 'CATNO') return 'CATALOGNUMBER'
  if (raw === 'BARCODE') return 'UPC'
  if (raw === 'DESCRIPTION') return 'COMMENT'
  if (raw === 'URLS' || raw === 'WWW' || raw === 'WEBSITE') return 'URL'
  return raw
}

async function replaceGeneratedFixture(stagedRelease: string): Promise<void> {
  try {
    const marker = await readFile(join(DESTINATION, 'GRAVLAX TAGGING FIXTURE.txt'), 'utf8')
    if (!marker.startsWith(MARKER)) {
      throw new Error(`Refusing to replace ${DESTINATION}: it was not made by this script.`)
    }
    await rm(DESTINATION, { recursive: true })
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  await rename(stagedRelease, DESTINATION)
}

async function ensureTool(name: string): Promise<void> {
  try {
    await run(name, ['--version'])
  } catch {
    throw new Error(`${name} is required to build the tagging fixture.`)
  }
}

async function run(command: string, args: string[]): Promise<void> {
  const child = Bun.spawn([command, ...args], {
    stdout: 'ignore',
    stderr: 'pipe'
  })
  const stderr = await new Response(child.stderr).text()
  const exitCode = await child.exited
  if (exitCode !== 0) {
    throw new Error(`${command} failed (${exitCode}): ${stderr.trim()}`)
  }
}

async function writeToneWav(path: string): Promise<void> {
  const sampleRate = 44_100
  const channels = 2
  const bitsPerSample = 16
  const bytesPerSample = bitsPerSample / 8
  const sampleCount = Math.floor(sampleRate / 4)
  const dataSize = sampleCount * channels * bytesPerSample
  const wav = Buffer.alloc(44 + dataSize)

  wav.write('RIFF', 0)
  wav.writeUInt32LE(36 + dataSize, 4)
  wav.write('WAVE', 8)
  wav.write('fmt ', 12)
  wav.writeUInt32LE(16, 16)
  wav.writeUInt16LE(1, 20)
  wav.writeUInt16LE(channels, 22)
  wav.writeUInt32LE(sampleRate, 24)
  wav.writeUInt32LE(sampleRate * channels * bytesPerSample, 28)
  wav.writeUInt16LE(channels * bytesPerSample, 32)
  wav.writeUInt16LE(bitsPerSample, 34)
  wav.write('data', 36)
  wav.writeUInt32LE(dataSize, 40)

  for (let frame = 0; frame < sampleCount; frame++) {
    const value = Math.round(Math.sin((frame * 2 * Math.PI * 440) / sampleRate) * 8_000)
    for (let channel = 0; channel < channels; channel++) {
      wav.writeInt16LE(value, 44 + (frame * channels + channel) * bytesPerSample)
    }
  }
  await writeFile(path, wav)
}

function fixtureNotes(): string {
  return `${MARKER}

This is one valid, short, two-disc FLAC release for manual end-to-end tests.
Never submit it to a tracker.

What it covers
- Various Artists album with changing track artists.
- Classical composer and conductor roles.
- A conductor duplicated in ARTIST, both with and without another main artist.
- One person as both main artist and composer.
- Composer names with commas and ampersands; semicolon and slash role separators.
- Featured artists in ARTIST and TITLE, including the four-guest "Various" write rule.
- Slash totals in track and disc numbers, spaced tag aliases, and a missing track number.
- Missing ALBUMARTIST on one track and ARTIST fallback to ALBUMARTIST on another.
- Composed/decomposed Unicode, case, and straight/smart-apostrophe duplicates.
- Punctuation that makes generic ARTIST splitting hard: AC/DC and Earth, Wind & Fire.
- Mixed genre, label, URL, and year values.
- An embedded picture block plus legacy COVERART tags.
- ISRC, ReplayGain, custom, producer, arranger, remixer, and DJ tags that Gravlax must not erase.

Focused current-change checks
1. Track 1 should show North Sea Orchestra [main], Ada Lovelace [conductor], and
   Bach, Johann Sebastian [composer]. Ada must not also show as main.
2. Track 2 should keep Adele as both [main] and [composer].
3. Track 3 should keep Solo Maestro as both [main] and [conductor], since removing
   its only main role would leave no lead artist.
4. Track 4 should keep Earth, Wind & Fire and Maestro, Jr. as whole role names,
   split Writer One/Two/Three, and remove the case-only Writer One duplicate.
5. Release credits should keep Various Artists [main], turn track-only main artists
   into [guest], and keep composer/conductor roles separate.
6. With Manual metadata, apply tags and inspect with metaflac. COMPOSER and CONDUCTOR
   should become separate repeatable comments, while cover and unmanaged tags stay.
7. On track 6, remove Legacy Lead [main] in the editor but keep No Lead Writer
   [composer], then apply. Its old ARTIST=Legacy Lead must remain on disk.
8. Restore original files. All odd source tags and cover data should return.

Expected deliberate rough edges
- The source year, label, genres, and URLs are mixed, so the current column says mixed.
- Track 8 reveals how a plain ARTIST string cannot tell separators from punctuation.
- Track 12 has no track number; the filename plan should use its file order as fallback.
`
}
